# Generated by Django 4.0.4 on 2022-05-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='menu',
            field=models.ManyToManyField(to='menu.menu'),
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
