# Generated by Django 4.0.4 on 2022-05-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menu',
            table='menus',
        ),
    ]
